%DEFINE CROSSOVER_BUFFER				0x5B00
%DEFINE CONFIG_START					0x5C00

%DEFINE CFG_DLG_OUTER_COLOUR				CONFIG_START
%DEFINE CFG_DLG_INNER_COLOUR				CONFIG_START + 0x02
%DEFINE CFG_DLG_SELECT_COLOUR				CONFIG_START + 0x04
%DEFINE CFG_TITLEBAR_COLOUR				CONFIG_START + 0x06
%DEFINE	CFG_24H_TIME					CONFIG_START + 0x08
%DEFINE CFG_DATE_FMT					CONFIG_START + 0x0A
%DEFINE CFG_DATE_SEPARATOR				CONFIG_START + 0x0C
%DEFINE CFG_SCREEN_HEIGHT				CONFIG_START + 0x0E
%DEFINE CFG_SCREEN_WIDTH				CONFIG_START + 0x10


